{
 "title": "Cloud Security Detection Platform",
 "time": { "from": "2024-10-19T03:50:49.082Z", "to": "2027-08-09T03:50:49.082Z" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "queryMode": "Metrics", "region": "default" }
   ]
  },
  {
   "title": "Attaques par heure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\r\n| filter @message like /REJECT/\r\n| stats count(*) as attaques by bin(1h)\r\n| sort @timestamp asc",
     "logGroups": [
      {
       "accountId": "798329741052",
       "arn": "arn:aws:logs:us-west-1:798329741052:log-group:/aws/cloudtrail/cloud-sec-trail:*",
       "name": "/aws/cloudtrail/cloud-sec-trail"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "Total IPs Suspectes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message\r\n| filter @message like /REJECT/\r\n| parse @message \"* * * * * * * * * * * * * *\" as version, account, eni, srcip, dstip, srcport, dstport, protocol, packets, bytes, start, end, action, status\r\n| stats count_distinct(srcip) as total_ips",
     "logGroups": [
      {
       "accountId": "798329741052",
       "arn": "arn:aws:logs:us-west-1:798329741052:log-group:/aws/cloudtrail/cloud-sec-trail:*",
       "name": "/aws/cloudtrail/cloud-sec-trail"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top 10 IPs Suspectes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\r\n| filter @message like /REJECT/\r\n| parse @message \"* * * * * * * * * * * * * *\" as version, account, eni, srcip, dstip, srcport, dstport, protocol, packets, bytes, start, end, action, status\r\n| stats count(*) as tentatives by srcip\r\n| sort tentatives desc\r\n| limit 10",
     "logGroups": [
      {
       "accountId": "798329741052",
       "arn": "arn:aws:logs:us-west-1:798329741052:log-group:/aws/cloudtrail/cloud-sec-trail:*",
       "name": "/aws/cloudtrail/cloud-sec-trail"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "srcip" ]
    }
   ]
  },
  {
   "title": "Connexions REJECT par 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\r\n| filter @message like /REJECT/\r\n| stats count(*) as connexions by bin(5m)\r\n| sort @timestamp desc",
     "logGroups": [
      {
       "accountId": "798329741052",
       "arn": "arn:aws:logs:us-west-1:798329741052:log-group:/aws/cloudtrail/cloud-sec-trail:*",
       "name": "/aws/cloudtrail/cloud-sec-trail"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  }
 ]
}