apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch
    jsonData:
      authType: default
      defaultRegion: us-west-1
    isDefault: true
    editable: true
